### ISSUE TITLE
Rename sandbox and move to a different directory. 

### ISSUE THREAD

**Issue by sallycr** [michelangelo-ai/michelangelo#23]
> We might want to rename sandbox and move to a different directory. But we can make the changes separately.

any alternative way do you want to propose? I browse many others and everyone has own way. but I like the approach of 'mactl demo start' in flytectl does or mlflow does 'mlflow server ...'

_Originally posted by @sallycr in https://github.com/michelangelo-ai/michelangelo/issues/19#issuecomment-2552575868_

**Comment by sallycr** [comment]
Check for other open source projects, 

[mlflow] https://mlflow.org/docs/latest/getting-started/intro-quickstart/index.html 
- pip install mlflow 
- mlflow server --host 127.0.0.1 --port 8080

[flyte] https://docs.flyte.org/projects/flytectl/en/latest/gen/flytectl_sandbox_start.html
- brew install flyteorg/homebrew-tap/flytectl
- flytectl sandbox start 

[kind] https://kind.sigs.k8s.io/docs/user/quick-start/ 
- brew install kind 
- brew install kubectl 
- kind create cluster
- kubectl cluster-info --context kind-kind
- kind delete cluster

**Comment by sallycr** [comment]
> ```
>           > We might want to rename sandbox and move to a different directory. But we can make the changes separately.
> ```
> 
> any alternative way do you want to propose? I browse many others and everyone has own way. but I like the approach of 'mactl demo start' in flytectl does or mlflow does 'mlflow server ...'
> 
> _Originally posted by [@sallycr](https://github.com/sallycr) in [#19 (comment)](https://github.com/michelangelo-ai/michelangelo/pull/19#issuecomment-2552575868)_

**Comment by badcount** [comment]
Can we use mactl to do sandbox?
